# Linear Regression
  
    ## given a groupd of data(x, y), use in placeholder
    ## assuming some random number parameters W and b for this linear y_predict = W*x + b
    ## where w and b are variables
    ## a good W and b will generate smaller error (= y_predict - y)
    ## the best W and b will have no error.


    ## Given Data: x: [1, 2, 3, 4], y: [0, 1, 2, 3]


    ## This is the solution which has no error: W = 1 and b= -1
    ## i.e.  y = W*x + b = x - 1
         

In [3]:
# linear function without regression

# given a groupd of data(x, y), there are in placeholder
# assuming some random number parameters w and b for this linear y_predict = w*x + b
# where w and b are variables
# a good w and b will generate smaller error (= y_predict - y)

import tensorflow as tf
# Model parameters, randomly pick w and b
W = tf.Variable([.1], dtype=tf.float32)
b = tf.Variable([.3], dtype=tf.float32)

# provided data
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)


#current model
linear_model = W*x + b


diff = linear_model - y
squared_deltas = tf.square(linear_model - y)

#A loss function measures how far apart the current model is from the provided data 
loss = tf.reduce_sum(squared_deltas)



sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
# or jointed to one line
#sess.run(tf.global_variables_initializer())




#A loss function measures how far apart the current model is from the provided data 
print("loss=", sess.run(loss, {x: [1, 2, 3, 4], y: [0, 1, 2, 3]}))
print("diff=", sess.run(diff,{x: [1, 2, 3, 4], y: [0, 1, 2, 3]}))


fixW = tf.assign(W, [1.]) 
fixb = tf.assign(b, [-1.])
linear_model = fixW*x + fixb
sess.run([fixW, fixb]) # this change will be used to replace w and b
print("loss=", sess.run(loss, {x: [1, 2, 3, 4], y: [0, 1, 2, 3]}))

sess.close()

loss= 7.66
diff= [ 0.4 -0.5 -1.4 -2.3]
loss= 0.0


In [1]:
# linear regression: complete code

# TensorFlow provides optimizers that slowly change w and b in order to minimize the loss function. 
# The simplest optimizer is gradient descent


import tensorflow as tf


W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)

# Model input and output
x = tf.placeholder(tf.float32)
linear_model = W*x + b
y = tf.placeholder(tf.float32)

# loss
loss = tf.reduce_sum(tf.square(linear_model - y)) # sum of the squares error



# optimizer
optimizer = tf.train.GradientDescentOptimizer(0.01) # steplength or rate = 0.01, you can change it
train = optimizer.minimize(loss)

# training data
x_train = [1, 2, 3, 4]
y_train = [0, 1, 2, 3]


# training loop
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init) # reset values to wrong


for i in range(1000):                          # total iteration or loop, you can change it to dif. number
    
    _, _, _, loss_value = sess.run((W, b,train, loss), {x: x_train, y: y_train})
    if( i%50 == 0 ):
        print("loss = ", loss_value)

# evaluate training accuracy
curr_W, curr_b, curr_loss = sess.run([W, b, loss], {x: x_train, y: y_train})
print("Fianl: W: %s b: %s loss: %s" %(curr_W, curr_b, curr_loss))



loss =  6.859999
loss =  0.14157227
loss =  0.042436995
loss =  0.012720684
loss =  0.0038131194
loss =  0.0011430006
loss =  0.00034262173
loss =  0.00010269877
loss =  3.078457e-05
loss =  9.228415e-06
loss =  2.7659194e-06
loss =  8.2905495e-07
loss =  2.484262e-07
loss =  7.451081e-08
loss =  2.2337208e-08
loss =  6.681944e-09
loss =  2.0090916e-09
loss =  6.025296e-10
loss =  1.7677237e-10
loss =  5.416112e-11
Fianl: W: [0.9999983] b: [-0.99999493] loss: 1.762146e-11


In [2]:
# https://www.tensorflow.org/programmers_guide/low_level_intro


# linear_model = tf.layers.Dense(units=1)  # one neuron unit = W*x + b

import tensorflow as tf


x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(0.01) # there are other optimizer
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(1000):
  _, loss_value = sess.run((train, loss))
  if i%100 == 0: 
        print("loss =", loss_value)
        print(sess.run(y_pred)) # the predict y value with w

loss = 10.70754
[[0.28508  ]
 [0.6261025]
 [0.967125 ]
 [1.3081474]]
loss = 0.16942152
[[-0.6626306]
 [-1.32109  ]
 [-1.9795493]
 [-2.6380086]]
loss = 0.093010366
[[-0.49096766]
 [-1.2379074 ]
 [-1.9848473 ]
 [-2.731787  ]]
loss = 0.05106155
[[-0.36377624]
 [-1.1762745 ]
 [-1.9887727 ]
 [-2.801271  ]]
loss = 0.028032178
[[-0.2695353]
 [-1.1306083]
 [-1.9916811]
 [-2.852754 ]]
loss = 0.015389334
[[-0.19970888]
 [-1.0967727 ]
 [-1.9938366 ]
 [-2.8909004 ]]
loss = 0.008448554
[[-0.14797163]
 [-1.0717024 ]
 [-1.995433  ]
 [-2.9191637 ]]
loss = 0.004638157
[[-0.10963768]
 [-1.0531269 ]
 [-1.9966161 ]
 [-2.9401054 ]]
loss = 0.0025462857
[[-0.08123457]
 [-1.0393637 ]
 [-1.9974929 ]
 [-2.9556222 ]]
loss = 0.0013978713
[[-0.06018955]
 [-1.029166  ]
 [-1.9981424 ]
 [-2.9671187 ]]


In [4]:
## https://www.tensorflow.org/versions/r1.0/get_started/get_started


import tensorflow as tf
# NumPy is often used to load, manipulate and preprocess data.
import numpy as np

# Declare list of features. We only have one real-valued feature. There are many
# other types of columns that are more complicated and useful.
features = [tf.contrib.layers.real_valued_column("x", dimension=1)]

# An estimator is the front end to invoke training (fitting) and evaluation
# (inference). There are many predefined types like linear regression,
# logistic regression, linear classification, logistic classification, and
# many neural network classifiers and regressors. The following code
# provides an estimator that does linear regression.
estimator = tf.contrib.learn.LinearRegressor(feature_columns=features)

# TensorFlow provides many helper methods to read and set up data sets.
# Here we use `numpy_input_fn`. We have to tell the function how many batches
# of data (num_epochs) we want and how big each batch should be.
x = np.array([1., 2., 3., 4.])
y = np.array([0., -1., -2., -3.])
input_fn = tf.contrib.learn.io.numpy_input_fn({"x":x}, y, batch_size=4,
                                              num_epochs=1000)

# We can invoke 1000 training steps by invoking the `fit` method and passing the
# training data set.
estimator.fit(input_fn=input_fn, steps=1000)

# Here we evaluate how well our model did. In a real example, we would want
# to use a separate validation and testing data set to avoid overfitting.
estimator.evaluate(input_fn=input_fn)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001B8067ED7B8>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': 'C:\\Users\\sun\\AppData\\Local\\Temp\\tmpbntz3r9w'}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\sun\AppData\Local\Temp\tmpbntz3r9w\mod

{'loss': 1.3495969e-05, 'global_step': 1000}